# Generated by Django 5.2.13 on 2026-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('receipt_editor', 'Receipt editor'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
