# Generated by Django 5.2.14 on 2026-05-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('luxury', 'Luxury'), ('tech', 'Technology'), ('shop', 'Shop'), ('services', 'Services')], db_index=True, max_length=32)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Marketing product categories',
                'ordering': ['page', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketingProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('luxury', 'Luxury'), ('tech', 'Technology'), ('shop', 'Shop'), ('services', 'Services')], db_index=True, max_length=32)),
                ('title', models.JSONField(blank=True, default=dict)),
                ('tag', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing-products/%Y/%m/')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('tone', models.CharField(choices=[('violet', 'Violet'), ('cyan', 'Cyan'), ('gold', 'Gold'), ('indigo', 'Indigo')], default='violet', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketing.marketingproductcategory')),
            ],
            options={
                'ordering': ['page', 'sort_order', 'id'],
            },
        ),
    ]
