# Generated by Django 5.2.13 on 2026-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopsettings_receipt_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='purchase_receipt_seq',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
