# Generated by Django 5.2.13 on 2026-04-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_receiptsettings_receipt_qr_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='purchase_receipt_seq',
        ),
    ]
