# Generated by Django 5.2.13 on 2026-05-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_remove_shop_purchase_receipt_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'permissions': [('view_profitreport', 'Can view profit report')]},
        ),
    ]
