# Generated by Django 5.2.13 on 2026-05-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_profit_report_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={
                'ordering': ['name'],
                'permissions': [
                    ('view_profitreport', 'Can view profit report'),
                    ('view_cashier', 'Can use cashier (Qasa)'),
                ],
            },
        ),
    ]
