# Generated by Django 5.2.14 on 2026-05-31 10:19

import django.core.validators
import django.db.models.deletion
import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_qr_manager_telegram'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shop',
            name='uniq_shop_storefront_host_when_set',
        ),
        migrations.AlterField(
            model_name='qrlandingsettings',
            name='preset_links',
            field=models.JSONField(default=shops.models._default_qr_preset_links),
        ),
        migrations.AlterField(
            model_name='shop',
            name='online_storefront_enabled',
            field=models.BooleanField(default=False, help_text='Public online catalog + checkout for this shop.'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='storefront_host',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Customer-facing host, e.g. rada.mmiraq.com (unique when set).', max_length=255),
        ),
        migrations.AlterField(
            model_name='storefrontbanner',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='storefrontsettings',
            name='delivery_free_min_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Subtotal (USD) at or above this gets free delivery; null/0 = off.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storefrontsettings',
            name='header_show_shop_name',
            field=models.BooleanField(default=False, help_text='If catalog title is empty, show shop legal name in the storefront header.'),
        ),
        migrations.AlterField(
            model_name='storefrontsettings',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
