# Generated by Django 5.2.13 on 2026-04-17 00:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_received_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_iqd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_discount_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saleline',
            name='unit_buy_price_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('exchange_rate_usd_to_iqd', models.DecimalField(blank=True, decimal_places=4, help_text='Required when currency is IQD: IQD per 1 USD at entry time.', max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
    ]
