# Generated by Django 5.2.13 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shareholders_debt_opening_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
