# Generated by Django 5.2.13 on 2026-04-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_customer_requires_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='manual_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='inventory.product'),
        ),
    ]
