# Generated by Django 5.2.14 on 2026-05-31 10:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_shareholderpayment'),
        ('shops', '0028_remove_shop_uniq_shop_storefront_host_when_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_ku', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='uniq_purchase_shop_invoice_number_when_set',
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='capital_contribution_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Partner capital recorded in the system (USD).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__gt', '')), fields=('shop', 'invoice_number'), name='uniq_purchase_shop_invoice_number_when_set'),
        ),
    ]
