# Generated by Django 5.2.14 on 2026-06-07 22:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_customer_debt_discount_writeoff'),
        ('shops', '0028_remove_shop_uniq_shop_storefront_host_when_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebtdiscountwriteoff',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.CreateModel(
            name='CustomerDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('amount_paid_iqd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('exchange_rate_usd_to_iqd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='inventory.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDebtPaymentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='inventory.customerdebtpayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payment_lines', to='inventory.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payment', 'sale'), name='uniq_debt_payment_sale_line')],
            },
        ),
    ]
